### ISSUE TITLE
Replace require() used to load 3D font with THREE.FontLoader()

### ISSUE THREAD

**Issue by rezib** [rackslab/Slurm-web#115]
Currently, there is a require() in a middle of this script to load the 3D font:

https://github.com/edf-hpc/slurm-web/blob/master/js/draw/3d-draw.js#L487

This is not very clean, it is not a common pattern, and it must be considered as a technical debt.
The three.js approach is to use THREE.FontLoader() instead.

We should study the feasibility to use it in place.

**Comment by Aenohe** [comment]
Salut, concernant la 115.

J’ai essayé plusieurs choses, la première était de sortir le require de la font dans le shim, la config ou les packages require, malheureusement le seul “chargement à la volé de require” nécessite d’avoir au préalable exporter la font dans le path require. Cette fonctionnalité sert dans les cas de chargement dynamique de template. On ne peut pas charger un fichier .js depuis un chemin renseigné dans la config elle même charger avant.

J’ai essayé de contourner en faisant un plugin, le problème c’est que je récupère le .js en plain text et pour le charger je doit faire un exec js, ce que je ne recommande pas. En plus d’être moche, cette solution est une mauvaise pratique.

Mon dernier test à été d’extraire le loader FontLoader de three js 74, pour voir s’il peut fonctionner avec Three 72, mais non, en plus d’avoir besoin de nouvelle fonctionnalité du core, il requiert une font exporter en json (nouvelle fonctionnalité en date du 3 mars de Facetype, voir merge PR 8)

Je pense que niveau élégance, la solution actuelle est la mieux, même s’il n’est pas commun, c’est parfaitement valide.

**Comment by LaanstraGJ** [comment]
three.js r73 has problems with displaying the rackname in 3d-view.
Switched to three.js r74 and replacing the require() with FontLoader and one of the three.js font files (helvetiker_bold.typeface.js) likes to work with the following changes in 3d-draw.js L488 :

      var loader = new THREE.FontLoader();
      loader.load(config.RACKNAME.FONT.PATH, function(font) {
        var geometry = new THREE.TextGeometry(rack.name, {
            font: font,
            size: config.UNITSIZE * config.RACKNAME.SIZE,
            height: config.UNITSIZE * config.RACKNAME.DEPTH
          }); // TextGeometry
        var material, mesh;

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
