### ISSUE TITLE
Show authorized clusters only

### ISSUE THREAD

**Issue by mehdid** [rackslab/Slurm-web#142]
When a user lands on the dashboard (and even after connection), all configured clusters all shown. A user might have access to a subset only. So it doesn't seem relevant to show the full list of clusters.

So we can imagine implemeting the following:
- Only clusters with role "all" or "guest" enabled are shown
- Authorized clusters for the user are shown once logged in.

**Comment by rezib** [comment]
To be considered with #128 in mind.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
