### ISSUE TITLE
No login screen when opening the page

### ISSUE THREAD

**Issue by hmlth** [rackslab/Slurm-web#163]
When opening the page with chromium (fresh incognito mode window) on Jessie, there is no login screen. I have to "logout" and then login again manually.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.
