### ISSUE TITLE
RESTAPI Giving Python exceptions on RHEL 7.3

### ISSUE THREAD

**Issue by bviviano** [rackslab/Slurm-web#174]
I am attempting to get slurm-web running on my RHEL7.3 cluster using Slurm 16.05.8.  I've worked through many of the Debian/Umbuntu dependencies but I am getting errors from the RESTAPI for sinfo (The other RESTAPI functions are working).  My Apache log is showing:

[Thu Jun 22 09:48:43.596233 2017] [:error] [pid 8245] ERROR:slurmrestapi:Exception on /sinfo [GET]
[Thu Jun 22 09:48:43.596254 2017] [:error] [pid 8245] Traceback (most recent call last):
[Thu Jun 22 09:48:43.596258 2017] [:error] [pid 8245]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu Jun 22 09:48:43.596261 2017] [:error] [pid 8245]     response = self.full_dispatch_request()
[Thu Jun 22 09:48:43.596264 2017] [:error] [pid 8245]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Jun 22 09:48:43.596267 2017] [:error] [pid 8245]     rv = self.handle_user_exception(e)
[Thu Jun 22 09:48:43.596270 2017] [:error] [pid 8245]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Jun 22 09:48:43.596280 2017] [:error] [pid 8245]     reraise(exc_type, exc_value, tb)
[Thu Jun 22 09:48:43.596283 2017] [:error] [pid 8245]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Jun 22 09:48:43.596286 2017] [:error] [pid 8245]     rv = self.dispatch_request()
[Thu Jun 22 09:48:43.596289 2017] [:error] [pid 8245]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu Jun 22 09:48:43.596292 2017] [:error] [pid 8245]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Jun 22 09:48:43.596294 2017] [:error] [pid 8245]   File "/usr/share/slurm-web/restapi/cors.py", line 53, in wrapped_function
[Thu Jun 22 09:48:43.596297 2017] [:error] [pid 8245]     resp = make_response(f(*args, **kwargs))
[Thu Jun 22 09:48:43.596310 2017] [:error] [pid 8245]   File "/usr/share/slurm-web/restapi/auth.py", line 287, in inner
[Thu Jun 22 09:48:43.596313 2017] [:error] [pid 8245]     resp = f(*args, **kwargs)
[Thu Jun 22 09:48:43.596316 2017] [:error] [pid 8245]   File "/usr/share/slurm-web/restapi/slurmrestapi.py", line 480, in sinfo
[Thu Jun 22 09:48:43.596319 2017] [:error] [pid 8245]     return make_response(json.dumps(resp), mimetype='application/json')
[Thu Jun 22 09:48:43.596321 2017] [:error] [pid 8245] NameError: global name 'make_response' is not defined

I noticed that slurmrestapi.py isn't including "make_response" in "from flask import".  However, if I add make_response I get a different error:

[Thu Jun 22 09:40:35.534279 2017] [:error] [pid 172584]   File "/atmos/www/html/slurm-web/restapi/slurmrestapi.py", line 481, in sinfo
[Thu Jun 22 09:40:35.534282 2017] [:error] [pid 172584]     
[Thu Jun 22 09:40:35.534284 2017] [:error] [pid 172584] TypeError: make_response() got an unexpected keyword argument 'mimetype'

I am using:

# rpm -qa| grep flask
python-flask-0.10.1-4.el7.noarch

**Comment by Pteresa** [comment]
I have encountered the same problem. Did you found any solution on this?

**Comment by bviviano** [comment]
Review the installation procedure I detailed in [ticket 169](https://github.com/edf-hpc/slurm-web/issues/169) for how I installed Slurm-web on my RHEL7 system.  My cluster is currently at RHEL 7.5, latest yum patches and everything is still operational for me.  However, I have not upgraded Slrum-web since I did the initial install at version 2.2.2, so I can't comment on anything that's changed in 2.2.3 and RHEL7.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on RHEL 8 with RPM packages. For older versions, we plan to distribute containers and this effort is tracked in https://github.com/rackslab/Slurm-web/issues/266.

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
