### ISSUE TITLE
dockerfile build

### ISSUE THREAD

**Issue by mspiffy** [rackslab/Slurm-web#188]
running the docker container I get a page rendering the below. I’ve attached the docker build output run on Debian 9/current. There are no obvious exceptions but on something around apache2_invoke. Any hints? 

![image](https://user-images.githubusercontent.com/25153649/35000337-71ab7202-fae4-11e7-8b66-57f999b0227f.png)

[slurmwebdebug.txt](https://github.com/edf-hpc/slurm-web/files/1635961/slurmwebdebug.txt)

**Comment by cleverchou** [comment]
I have the file "dockerfile" , after runing "docker build -t slurm-web"  , I get the same page

**Comment by rezib** [comment]
Have you checked PySlurm works with your slurm version inside your container? This is a requirement from slurm-web.

You can also check for useful error messages in apache error logs.

**Comment by QwertyJack** [comment]
Same problem at Centos 7.
The docker log is OK, but blank page.

**Comment by nichoice** [comment]
> Centos 7 
> 的问题相同。泊坞窗日志没问题，但空白页面。

同样的问题，你的解决了么

**Comment by QwertyJack** [comment]
老哥你真逗

> > Centos 7
> > 的问题相同。泊坞窗日志没问题，但空白页面。
> 
> 同样的问题，你的解决了么

老哥你真逗

**Comment by mehdid** [comment]
There are two things you may check in order to debug this issue:
1) test pyslurm in a python interpreter from within your docker container. If my memory serves me right, "import pyslurm; pyslurm.job.get()" will give you some hint.
2) have a look at JavaScript errors in your web brower to see if there are useful hints/errors.

Are you able to make those checks?

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on many distributions with RPM and deb packages. If you prefer containers, we plan to work on this in https://github.com/rackslab/Slurm-web/issues/266

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
