### ISSUE TITLE
white page 

### ISSUE THREAD

**Issue by cleverchou** [rackslab/Slurm-web#189]
I am new to this stuff but while finishing installation following the guide.
I get the white page , can anybody help??

**Comment by cleverchou** [comment]
after runing "docker build -t slurm-web",  docker start sucessful , but the html page is nothing

**Comment by cleverchou** [comment]
after runing "./run.sh" , docker container is starting, but can't attach it .
by the browser,this is white page

**Comment by cleverchou** [comment]
after runing "./run.sh" , docker container is starting, but can't attach it .
![img_20180122_153113_resized_20180122_033633715](https://user-images.githubusercontent.com/34674754/35210255-6851a6a4-ff49-11e7-91e2-ea6608e132f8.jpg)

by the browser,this is white page
![img_20180122_153556_resized_20180122_033633423](https://user-images.githubusercontent.com/34674754/35210280-7d3923a8-ff49-11e7-8379-4fc3a360de09.jpg)

**Comment by rezib** [comment]
Have you checked PySlurm works with your slurm version inside your container? This is a requirement from slurm-web.

You can also check for useful error messages in apache error logs.

**Comment by cleverchou** [comment]
my slurm version is 17.02.9, I change the Dockerfile , then get the error:
![124](https://user-images.githubusercontent.com/34674754/35337348-e1b5882c-0155-11e8-938a-aa723eaf2ae9.jpg)

**Comment by rezib** [comment]
The script is trying to checkout PySLURM remote 17.02.9 branch which does not exist. The branch is named 17.02.0: https://github.com/PySlurm/pyslurm/tree/17.02.0

**Comment by cleverchou** [comment]
My slurm server vision: 17.02.9
I change the file Dockerfile following:"ENV SLURM_VER=17.02.0"
after running "docker build -t slurm-web ." , this is ERROR
what's the "__max_slurm_hex_version__" mean? how to modify ?

**Comment by liuxiaopiao** [comment]
met the same issue after changing SLURM_VER to 17.02.0. Has anyone figured out this issue>

**Comment by mehdid** [comment]
max_slurm_hex_version is max slurm version in hexadecimal set in pyslurm's sources. 0x0f0803 means the pyslurm version you're looking at is compatible with Slurm 15.08.03, at most. Does this hint help?

You have to make sure the build script chooses the right pyslurm branch to make sure it is compatible with you slurm version. You will find `__max_slurm_hex_version__` defined in pyslurm's `setup.py`.

**Comment by albertojmz** [comment]
Hi,

I have followed this post to install Slurm. The version used is 17.11.12. https://github.com/mknoxnv/ubuntu-slurm/blob/master/README.md

I have modified the Dockerfile to run the build docker command with the correct parameters and I always have the following error:

![Captura de pantalla 2021-04-23 a las 11 58 25](https://user-images.githubusercontent.com/26324552/115905128-4601bc80-a42b-11eb-8791-f41e8823196d.png)

I dont know if anyone has faced the same error

**Comment by andrewssobral** [comment]
Hello All,
I am facing the same issue, my slurm version is 19.05.5
It shows:
```
Step 14/30 : ENV SLURM_VER=19.05.0
 ---> Using cache
 ---> bc5529bfd3d8
Step 15/30 : RUN cd /usr/src &&     git clone https://github.com/PySlurm/pyslurm.git &&     cd pyslurm &&     git checkout remotes/origin/$SLURM_VER &&     tar cvfj ../python-pyslurm_$SLURM_VER.orig.tar.bz2 --exclude .git . &&     mk-build-deps -ri -t "apt-get -y --no-install-recommends" &&     dch -v $SLURM_VER-1 -D testing "New upstream release" &&     debuild -us -uc &&     dpkg -i ../python-pyslurm_$SLURM_VER-1_amd64.deb
 ---> Running in e44eb6518b07
Cloning into 'pyslurm'...
Note: checking out 'remotes/origin/19.05.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 0d5e23a... Return job steps from slurmdb_jobs.get #167 (#168)
./
./.github/
./.github/ISSUE_TEMPLATE.md
./examples/
./examples/reservation_list.py
./examples/triggers_list.py
./examples/hostlist.py
./examples/partition_delete.py
./examples/controllers.py
./examples/partition_list.py
./examples/triggers_set.py
./examples/slurm_ctl.py
./examples/debug_levels.py
./examples/checkpoint_job.py
./examples/job_test.py
./examples/slurm_xml.py
./examples/triggers_clear.py
./examples/sjobs.py
./examples/jobs_list.py
./examples/licenses.py
./examples/node_update.py
./examples/listdb_reservations.py
./examples/reservation_create.py
./examples/listdb_jobs.py
./examples/node_list.py
./examples/listdb_cluster.py
./examples/cancel_job.py
./examples/show-cluster-util.py
./examples/listdb_events.py
./examples/listdb_qos.py
./examples/blocks_list2.py
./examples/reservation_update.py
./examples/topo_list.py
./examples/partition_create.py
./examples/blocks_list.py
./examples/partition_update.py
./examples/reservation_delete.py
./examples/jobsteps_list.py
./examples/slurm_node_xml.py
./examples/jobsteps_layout.py
./examples/stats.py
./.pylintrc
./THANKS.rst
./MANIFEST.in
./CONTRIBUTORS.rst
./COPYING.txt
./.travis.yml
./README.rst
./pyslurm/
./pyslurm/xmalloc.h
./pyslurm/alps_cray.h
./pyslurm/__version__.py
./pyslurm/slurm.pxd
./pyslurm/pyslurm.pyx
./pyslurm/slurm_defines.pxi
./pyslurm/__init__.py
./tests/
./tests/test_slurmdb.py
./tests/test-job.py
./tests/common.py
./tests/test-license.py
./tests/test-qos.py
./tests/test-node.py
./tests/test-misc.py
./tests/test-hostlist.py
./tests/test-partition.py
./tests/test-statistics.py
./tests/test-topology.py
./tests/test-jobstep.py
./tests/test-reservation.py
./tests/test-config.py
./.gitignore
./setup.cfg
./setup.py
./doc/
./doc/doctrees/
./doc/doctrees/environment.pickle
./doc/doctrees/index.doctree
./doc/Makefile
./doc/source/
./doc/source/conf.py
./doc/source/index.rst
./doc/source/_static/
./doc/source/_static/pyslurm-docs.png
./scripts/
./scripts/run_tests.sh
./scripts/configure.sh
./scripts/builddocs.sh
./scripts/build.sh
Usage:
    mk-build-deps --help|--version

    mk-build-deps [*options*] *control file* | *package name* ...

The command '/bin/sh -c cd /usr/src &&     git clone https://github.com/PySlurm/pyslurm.git &&     cd pyslurm &&     git checkout remotes/origin/$SLURM_VER &&     tar cvfj ../python-pyslurm_$SLURM_VER.orig.tar.bz2 --exclude .git . &&     mk-build-deps -ri -t "apt-get -y --no-install-recommends" &&     dch -v $SLURM_VER-1 -D testing "New upstream release" &&     debuild -us -uc &&     dpkg -i ../python-pyslurm_$SLURM_VER-1_amd64.deb' returned a non-zero code: 1
```

The peace of code is:
```
# Build and install specific deps
ENV SLURM_VER=19.05.0
# sed -i 's/__max_slurm_hex_version__ = "0x0f0803"/__max_slurm_hex_version__ = "0x0f0807"/' setup.py && \
RUN cd /usr/src && \
    git clone https://github.com/PySlurm/pyslurm.git && \
    cd pyslurm && \
    git checkout remotes/origin/$SLURM_VER && \
    tar cvfj ../python-pyslurm_$SLURM_VER.orig.tar.bz2 --exclude .git . && \
    mk-build-deps -ri -t "apt-get -y --no-install-recommends" && \
    dch -v $SLURM_VER-1 -D testing "New upstream release" && \
    debuild -us -uc && \
    dpkg -i ../python-pyslurm_$SLURM_VER-1_amd64.deb
```

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on many distributions with RPM and deb packages. If you prefer containers, we plan to work on this in https://github.com/rackslab/Slurm-web/issues/266

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
