### ISSUE TITLE
Add a way to search for jobs using some specific wckey

### ISSUE THREAD

**Issue by mehdid** [rackslab/Slurm-web#193]
With #141, it became possible to click on a used wckey to use it as a filter in the jobs view. Another required method is to be able to enter the desired wckey directly into the search box (the same for other searchable fields).

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
