### ISSUE TITLE
Loading spinner just stays there after loading ended

### ISSUE THREAD

**Issue by hmlth** [rackslab/Slurm-web#194]
Sometimes, usually when the page has reloaded a few times. The spinner (the spinning circle during data load) stays above the page even after the loading ended and is never removed. Even when changing cluster. The only way to remove is to fully reload the page.

Firefox ESR 52.8.0 (64-bit) debian 9.

**Comment by hmlth** [comment]
Managed to reproduce : 

* Go to a large cluster jobsmap
* don't let it fully load
* Go back to job list
* The spinner for jobsmap stays on top

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
