### ISSUE TITLE
munge error

### ISSUE THREAD

**Issue by ugiwgh** [rackslab/Slurm-web#195]
[root@centos71611 slurm-web]# ./run2.sh 
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
munged: Error: Found pid 28 bound to socket "/var/run/munge/munge.socket.2"
^C*** Shutting down runit daemon (PID 9)...
*** Killing all processes...

**Comment by ssgtmccrae** [comment]
This is still an issue with the docker container on build v2.2.3

**Comment by mehdid** [comment]
Can you tell us how `run2.sh` is different from `run.sh` from slurm-web's git repository?
Did you try to debug munge installation?

**Comment by mehdid** [comment]
Additionally, can you test the fix described in #168 ?

**Comment by jamesmememes** [comment]
hello mehdid or anybody else who can help. I was hoping anybody could answer me some questions. 

I followed all the instructions from the page : https://edf-hpc.github.io/slurm-web/installation.html
I already have slurm working, but when I try to access the web interface through  http://localhost:8081/slurm an empty page shows up. 
can anybody tell me how to link slurm-web with slurm properly ? 

also, when I tried to run this command : 
apt-get install slurm-web-restapi slurm-web-dashboard

I get these erros : 
E: Unable to locate package slurm-web-restapi
E: Unable to locate package slurm-web-dashboard


I posted it in here, since I saw you're a developer and theres a lot of open issues right now. 
sorry to bother you, and any help would be really appreciate it.

**Comment by data-lab01** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package slurm-web-restapi
E: Unable to locate package slurm-web-dashboard

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
