### ISSUE TITLE
Missing slurm-web-conf/clusters.config.js

### ISSUE THREAD

**Issue by npow** [rackslab/Slurm-web#198]
I followed the installation guide and am running the docker container, but when I visit the website I'm getting an error about `slurm-web-conf/clusters.config.js` not found, so the site doesn't work. I don't see that file in the repo either. Is there a command to generate it somehow?

![image](https://user-images.githubusercontent.com/206201/47582716-0c0ed880-d90a-11e8-9944-de3c14103b37.png)

Probably not related, but I'm also seeing a lot of `munged: Error: Found pid 30 bound to socket "/var/run/munge/munge.socket.2"` messages in the docker logs.

I'm on Ubuntu 16.04.5 LTS and I'm using commit `a673eb804bc0ab2bf5c5f8927311c38f6d2427cc`.

**Comment by mehdid** [comment]
`clusters.config.js` is not stored in the Git repo, but is described in the installation manual which you can find here: http://edf-hpc.github.io/slurm-web/installation.html . You may generate one manually.

**Comment by mehdid** [comment]
Any news?

**Comment by asadz** [comment]
I have the same problem. The folder slurm-web-conf doesn't exist in the container. Even if I create it and add the clusters.config.js file I still get a blank screen.

**Comment by asadz** [comment]
Got it running in the end. Had to copy  clusters.config.js to a place apache could see it and edit the index.html to reflect the new location, also had to add redis-server to container and start it.

**Comment by hatschito** [comment]
Dear Asadz, I got the same issue on a native installation. In chrome in the consele I get the error: _Failed to load resource: the server responded with a status of 404 (NOT FOUND)_
To which location did you copy the clusters.config.js and what edits did you do in your index.html?

**Comment by asadz** [comment]
Hi Harald,

I gave up using the system as I couldn't get it working properly but..

I think I fixed that problem by changing the dockerfile and adding

#Fix problem with clusters.config.js path
RUN cd /usr/share/slurm-web/dashboard && \
    sed -i s@slurm-web-conf@slurm/web-conf@ index.html

and adding

mkdir /usr/share/slurm-web/dashboard/web-conf
cp /etc/slurm-web/clusters.config.js /usr/share/slurm-web/dashboard/web-conf

to apache2.sh

Chris


________________________________

**Comment by hatschito** [comment]
Hi Chris,
thanks a lot for your quick and helpful answer! I compiled it from source and try to run it natively, but run into the same or similar problems. Apache does not find several .json files. 

Do you use any other system to visualize a status of SLURM nodes?


Best Harald

**Comment by nothing-fr** [comment]
rename `$WORKDIR/conf/dashboard/cluster.config.json` to `$WORKDIR/conf/dashboard/cluster.config.js` in your workdir, it will work.
The `index.html` call `cluster.config.js` not `cluster.config.json` (typo?)

**Comment by nothing-fr** [comment]
Something is wrong with the project documentation...

I had to create `$ŴORKDIR/conf/dashboard/clusters.config.js` containing :
```
window.clusters = []
```

Now I have the page "working", but some errors with pyslurm : 
```
[Fri Jan 14 14:21:17.151083 2022] [wsgi:error] [pid 32:tid 139999346300672] ERROR:slurmrestapi:Exception on /jobs [POST]
[Fri Jan 14 14:21:17.151119 2022] [wsgi:error] [pid 32:tid 139999346300672] Traceback (most recent call last):
[Fri Jan 14 14:21:17.151128 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Fri Jan 14 14:21:17.151136 2022] [wsgi:error] [pid 32:tid 139999346300672]     response = self.full_dispatch_request()
[Fri Jan 14 14:21:17.151144 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Fri Jan 14 14:21:17.151152 2022] [wsgi:error] [pid 32:tid 139999346300672]     rv = self.handle_user_exception(e)
[Fri Jan 14 14:21:17.151159 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Fri Jan 14 14:21:17.151167 2022] [wsgi:error] [pid 32:tid 139999346300672]     reraise(exc_type, exc_value, tb)
[Fri Jan 14 14:21:17.151175 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Fri Jan 14 14:21:17.151182 2022] [wsgi:error] [pid 32:tid 139999346300672]     rv = self.dispatch_request()
[Fri Jan 14 14:21:17.151190 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Fri Jan 14 14:21:17.151197 2022] [wsgi:error] [pid 32:tid 139999346300672]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Jan 14 14:21:17.151205 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/cors.py", line 53, in wrapped_function
[Fri Jan 14 14:21:17.151212 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = make_response(f(*args, **kwargs))
[Fri Jan 14 14:21:17.151220 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/auth.py", line 207, in inner
[Fri Jan 14 14:21:17.151227 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = f(*args, **kwargs)
[Fri Jan 14 14:21:17.151235 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/cache.py", line 107, in inner
[Fri Jan 14 14:21:17.151242 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = f(*args, **kwargs)
[Fri Jan 14 14:21:17.151249 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/slurmrestapi.py", line 116, in get_jobs
[Fri Jan 14 14:21:17.151257 2022] [wsgi:error] [pid 32:tid 139999346300672]     jobs = pyslurm.job().get()
[Fri Jan 14 14:21:17.151264 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "pyslurm/pyslurm.pyx", line 1930, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:26987)
[Fri Jan 14 14:21:17.151272 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "pyslurm/pyslurm.pyx", line 1950, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:26939)
[Fri Jan 14 14:21:17.151280 2022] [wsgi:error] [pid 32:tid 139999346300672] ValueError: ('Zero Bytes were transmitted or received', 5005)
```

**Comment by KapilS25** [comment]
> Something is wrong with the project documentation... (I'm using the docker container)
> 
> I had to create `$WORKDIR/conf/dashboard/clusters.config.js` containing :
> 
> ```
> window.clusters = []
> ```
> 
> Should be `$WORKDIR/conf/dashboard/clusters.config.json` now if I understand correctly this issue : #139 ?
> 
> Something is wrong somewhere...
> 
> Now I have the page "working" 👍 ![image](https://user-images.githubusercontent.com/92157590/149532101-3377ea3e-1cf9-484e-a0b6-9a0f2218825c.png)
> 
> but some errors with pyslurm :
> 
> ```
> [Fri Jan 14 14:21:17.151083 2022] [wsgi:error] [pid 32:tid 139999346300672] ERROR:slurmrestapi:Exception on /jobs [POST]
> [Fri Jan 14 14:21:17.151119 2022] [wsgi:error] [pid 32:tid 139999346300672] Traceback (most recent call last):
> [Fri Jan 14 14:21:17.151128 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
> [Fri Jan 14 14:21:17.151136 2022] [wsgi:error] [pid 32:tid 139999346300672]     response = self.full_dispatch_request()
> [Fri Jan 14 14:21:17.151144 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
> [Fri Jan 14 14:21:17.151152 2022] [wsgi:error] [pid 32:tid 139999346300672]     rv = self.handle_user_exception(e)
> [Fri Jan 14 14:21:17.151159 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
> [Fri Jan 14 14:21:17.151167 2022] [wsgi:error] [pid 32:tid 139999346300672]     reraise(exc_type, exc_value, tb)
> [Fri Jan 14 14:21:17.151175 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
> [Fri Jan 14 14:21:17.151182 2022] [wsgi:error] [pid 32:tid 139999346300672]     rv = self.dispatch_request()
> [Fri Jan 14 14:21:17.151190 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
> [Fri Jan 14 14:21:17.151197 2022] [wsgi:error] [pid 32:tid 139999346300672]     return self.view_functions[rule.endpoint](**req.view_args)
> [Fri Jan 14 14:21:17.151205 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/cors.py", line 53, in wrapped_function
> [Fri Jan 14 14:21:17.151212 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = make_response(f(*args, **kwargs))
> [Fri Jan 14 14:21:17.151220 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/auth.py", line 207, in inner
> [Fri Jan 14 14:21:17.151227 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = f(*args, **kwargs)
> [Fri Jan 14 14:21:17.151235 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/cache.py", line 107, in inner
> [Fri Jan 14 14:21:17.151242 2022] [wsgi:error] [pid 32:tid 139999346300672]     resp = f(*args, **kwargs)
> [Fri Jan 14 14:21:17.151249 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "/usr/share/slurm-web/restapi/slurmrestapi.py", line 116, in get_jobs
> [Fri Jan 14 14:21:17.151257 2022] [wsgi:error] [pid 32:tid 139999346300672]     jobs = pyslurm.job().get()
> [Fri Jan 14 14:21:17.151264 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "pyslurm/pyslurm.pyx", line 1930, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:26987)
> [Fri Jan 14 14:21:17.151272 2022] [wsgi:error] [pid 32:tid 139999346300672]   File "pyslurm/pyslurm.pyx", line 1950, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:26939)
> [Fri Jan 14 14:21:17.151280 2022] [wsgi:error] [pid 32:tid 139999346300672] ValueError: ('Zero Bytes were transmitted or received', 5005)
> ```

Hi can you please share how you configure slurmrest api on your system ?
I am using jwt auth with slurmrestapi, stuck at how  the authentication will be done, we dont have ldap on our cluster.
Can you please help

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on many distributions with RPM and deb packages. If you prefer containers, we plan to work on this in https://github.com/rackslab/Slurm-web/issues/266

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
