### ISSUE TITLE
Slurm web does not work

### ISSUE THREAD

**Issue by marseaplage** [rackslab/Slurm-web#205]
I got these errors as a result the command:

 docker logs container_id

munged: Info: PRNG seeded with 1024 bytes from "/dev/urandom"
munged: Info: Updating supplementary group mapping every 3600 seconds
munged: Info: Enabled supplementary group mtime check of "/etc/group"
munged: Info: Removed existing socket "/var/run/munge/munge.socket.2"
munged: Notice: Starting munge-0.5.11 daemon (pid 19683)
munged: Info: Created 2 work threads
munged: Info: Failed to query password file entry for "ppito"
munged: Info: Found 2 users with supplementary groups in 0.001 seconds

ANd the webpage the slurm is trying to load but it is a blank page.
![slurm_web_intento2](https://user-images.githubusercontent.com/49536604/56322827-aae4f680-612f-11e9-8e77-ba231bb3f164.JPG)

**Comment by andrewssobral** [comment]
Hello All,
I am facing the same issue, here's my docker logs:
```
~/slurm-web$ docker logs --follow da61b7d4e346
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 10
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Aug 19 21:32:58 da61b7d4e346 syslog-ng[17]: syslog-ng starting up; version='3.5.6'
```
Everything seems OK, but the web interface doesn't work.
How can I solve it?


My run.sh:
```
data=$PWD
docker run -d -v $data/conf:/etc/slurm-web \
              -v /etc/munge:/etc/munge \
              -v /etc/slurm-llnl:/etc/slurm-llnl \
              -v /etc/passwd:/etc/passwd \
              -v /etc/group:/etc/group \
              -p 8081:80 \
              slurm-web
```

**Comment by andrewssobral** [comment]
More info about this issue:

![Screen Shot 2022-08-19 at 23 41 00](https://user-images.githubusercontent.com/483114/185711089-2f470001-28ae-45da-b842-3fca1227d914.png)

**Comment by BlackS52** [comment]
The same problem

**Comment by brandon-bagwell** [comment]
I just wanted to chime in that I received the same type of very-minimal output.  I followed the tutorial located here: https://edf-hpc.github.io/slurm-web/installation.html

Output is the same in FF, Chrome, and Edge.  

I'm happy to provide any diagnostic output that would be helpful.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on many distributions with RPM and deb packages. If you prefer containers, we plan to work on this in https://github.com/rackslab/Slurm-web/issues/266

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
