### ISSUE TITLE
Issues of  slurm-web configuration 

### ISSUE THREAD

**Issue by menyaoui** [rackslab/Slurm-web#206]
Hi,
I recently installed web-slurm on a centos 7 machine, and I have only three questions to ask
We have a couple of questions :

1- Is there  a way to show the login nodes or IO nodes on the rack view ?
We would have a view with the result of the sreport cluster command Is there a way to 2- implement it in the slurm web application ?
3- Is there a plugin or some thing like that ?

Thanks for your feedback
Riadh

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
