### ISSUE TITLE
Slurm-web apt install instructions produce dashboard spinning wheel

### ISSUE THREAD

**Issue by twh** [rackslab/Slurm-web#207]
I have followed the instructions which indicate that a Debian 9 install can be made into Scibian 9 by adding the repo.  I installed slurm-web according to the instructions and in noticed that the install does not add a link to javascript-common.conf in /etc/apache2/config-enabled directory. After adding this I can get the restapi to query info from slurm with no issues, but the dashboard will not load. I looked at the apache2 logs and noticed no major issues. I checked the racks.xml file and I'm sure that it is formatted correctly, but the dashboard still hangs with a spinning wheel. I have attached a Safari debug session here, but since I am not a JS dev I'm not sure what to look at next.
<img width="912" alt="Screen Shot 2019-06-05 at 3 39 12 PM" src="https://user-images.githubusercontent.com/997010/58985568-9fb25c80-87a9-11e9-9341-83c92c174eb3.png">
<img width="911" alt="Screen Shot 2019-06-05 at 3 51 52 PM" src="https://user-images.githubusercontent.com/997010/58985650-e011da80-87a9-11e9-92b0-10fc5a9a032a.png">
<img width="853" alt="Screen Shot 2019-06-05 at 7 11 32 PM" src="https://user-images.githubusercontent.com/997010/58996368-dd24e300-87c5-11e9-90c8-f287e8ebeb4a.png">

**Comment by twh** [comment]
Can anyone tell me what to look at or where the issue may be?

**Comment by pruchai** [comment]
@twh Most likely something in your `racks.xml` configuration file. Start with an empty config. I am running in the container and had to do whole lot of massaging to make it work.

**Comment by twh** [comment]
What did you have to massage, just the racks.xml? The API looks like it is parsing the data correctly as far as I can tell, but I cannot get the dashboard to do anything other that return the spinning wheel.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
