### ISSUE TITLE
Better step-by-step instruction

### ISSUE THREAD

**Issue by georges-nvidia** [rackslab/Slurm-web#209]
Weather using the docker (which is preferred) or the build/roll your own, a step by step guide will be good for the admins who are new to slurm and helping them get something functional running within a reasonable time. I rate the software as good, although it seems dated, but it is a daimond in the rough.

**Comment by bahaibilgiokyanusu** [comment]
I will be happy if my Centos can run it without docker. Also it is really necessary a guide for Centos 7.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
