### ISSUE TITLE
Redis port when running in docker?

### ISSUE THREAD

**Issue by NathanielMiddleton** [rackslab/Slurm-web#212]
I have been able to get some basic functionality of the slurm api to work (mainly the header) but beyond that seems to be blocked by redis not listening:

conf/restapi.conf references that it "default to host=localhost, port=6379"
but that didn't work:
"ConnectionError: Error -2 connecting to :6379. Name or service not known"

setting this specifically to localhost:
redis_host=localhost
redis_port=6379
results in : ConnectionError: Error 101 connecting to localhost:6379. Network is unreachable
(guessing that docker is not able to make that translation)
I tried just disabling caching which just resulted in:
"NameError: name 'redis_host' is not defined"

Where is the redis server configured to run? I must be missing something here...

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
