### ISSUE TITLE
Fails to build on Debian Bullseye

### ISSUE THREAD

**Issue by Compizfox** [rackslab/Slurm-web#213]
Hi,

I am trying to build and install slurm-web on Debian Bullseye as per [installation.rst](https://github.com/edf-hpc/slurm-web/blob/master/doc/installation.rst).

First, I encountered #130. I installed `node-opentypejs_0.4.3-2_all.deb` from https://people.debian.org/~ana/slurmweb/.

Now, I get the following error when trying to build slurm-web:

```
~/src/slurm-web# debuild -us -uc
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package slurm-web
dpkg-buildpackage: info: source version 2.2.6
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Frédéric Ballan <frederic-externe.ballan@edf.fr>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 debian/rules clean
dh clean --with apache2
dh: warning: Compatibility levels before 10 are deprecated (level 8 in use)
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/root/src/slurm-web'
rm -f dashboard/js/libraries/xdomain.min.js
rm -rf dashboard/js/fonts
make[1]: Leaving directory '/root/src/slurm-web'
   dh_clean
dh_clean: warning: Compatibility levels before 10 are deprecated (level 8 in use)
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building slurm-web in slurm-web_2.2.6.tar.xz
dpkg-source: info: building slurm-web in slurm-web_2.2.6.dsc
 debian/rules build
dh build --with apache2
dh: warning: Compatibility levels before 10 are deprecated (level 8 in use)
   dh_update_autotools_config
   debian/rules override_dh_auto_build
make[1]: Entering directory '/root/src/slurm-web'
uglifyjs -o dashboard/js/libraries/xdomain.min.js dashboard/js/libraries/xdomain.js
mkdir -p dashboard/js/fonts
nodejs /usr/lib/nodejs/font-converter.js /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf > dashboard/js/fonts/DejaVuSansMono.typeface.js
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/usr/lib/nodejs/package.json'
Require stack:
- /usr/lib/nodejs/font-converter.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/nodejs/font-converter.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/nodejs/font-converter.js' ]
}
make[1]: *** [debian/rules:9: override_dh_auto_build] Error 1
make[1]: Leaving directory '/root/src/slurm-web'
make: *** [debian/rules:4: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```
I am unsure how to proceed further. Am I missing another nodejs package?

**Comment by FlorianMF** [comment]
Same for me, but on Ubuntu 20.10

**Comment by jochym** [comment]
Same from me: debian buster. I actually succeeded to make a docker image with modified sources and it showed jobs list and correct 3D view but racks and jobs-map pages show no racks at all. Actually my previous install spontaneously stopped working in the same way.
Please make some updated build/install instructions. The present code has references to some ancient slurm versions and is not compatible with current jQuery and Flask. I have made some corrections but it is not working properly (https://github.com/jochym/slurm-web). This is really frustrating because it looks nice. 

Please provide some *working* example - otherwise all your work goes to waste essentially.

**Comment by garbled1** [comment]
Same problem here on bullseye.  It would be really nice if pre-build deb's were available for this.  I cannot get it to function.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. Prebuilt packages are available for all most popular Linux distributions, including Debian among others. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.
