### ISSUE TITLE
Add a filter to the jobs page(feature request)

### ISSUE THREAD

**Issue by fengpinghu** [rackslab/Slurm-web#215]
Would it make sense to add a filter to the jobs page?
The jobs page can take more than 1 minute to load and display when the number of jobs is 30k+. 
It would make the jobs page more responsive if jobs can be filtered on partitions, users etc

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
