### ISSUE TITLE
CENTOS 8-stream with docker: blank/white web page with a partial top menu

### ISSUE THREAD

**Issue by forgetfr** [rackslab/Slurm-web#221]
Hello,

We had set up a HPC with slurm based on CENTOS 8-stream for 500 students. It ROCKS!!!

Unfortunately, we are not able to set up slurm-web on the slurmctld master node. 

By default, CENTOS 8-stream use podman as the container engine BUT the compatibility is not 100% garanty with DockerFile. So we made some changes in the slurmctld master node to replace podman with docker.

We follow the instuctions as provide, but, the result isn't what, I belived, it should be.

The result is a white web page with only a blue arrow inside the the white menu on top of the page.

docker logs $containerID reports anything.

Any clue to where to start.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on CentOS 8 with RPM packages. If you prefer podman containers, we plan to work on this in https://github.com/rackslab/Slurm-web/issues/266.

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
