### ISSUE TITLE
CentOS-8.3 build slurm-web error

### ISSUE THREAD

**Issue by liu-shaobo** [rackslab/Slurm-web#223]
hi，all
[joe@10-75-26-86 slurm-web]$ mock --mount --isolation=simple --root centos-stream+epel-8-x86_64 --buildsrpm --Dependencies resolved.
Nothing to do.
Complete!
Finish: dnf update
Finish: chroot init
Start: buildsrpm
Start: rpmbuild -bs
error: Bad source: /builddir/build/SOURCES/slurm-web-2.4.0.tar.gz: No such file or directory
Building target platforms: x86_64
Building for target x86_64
Finish: rpmbuild -bs
Finish: buildsrpm
ERROR: Exception(rhel/slurm-web.spec) Config(centos-stream+epel-8-x86_64) 0 minutes 7 seconds
INFO: Results and/or logs in: result/
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: Command failed:
 # bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/slurm-web.spec

[joe@10-75-26-86 slurm-web]$ cat result/build.log
Mock Version: 3.0
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/slurm-web.spec'], chrootPath='/var/lib/mock/centos-stream+epel-8-x86_64/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f0bd87fa160>timeout=0uid=1000gid=135user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=True)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/slurm-web.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
error: Bad source: /builddir/build/SOURCES/slurm-web-2.4.0.tar.gz: No such file or directory
Building target platforms: x86_64
Building for target x86_64
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 598, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed:
 # bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/slurm-web.spec

**Comment by liu-shaobo** [comment]
[root@10-75-26-86 ~]# rpmbuild -tb slurm-web-2.4.0.tar.gz
error: %pycached can only be used with paths explicitly ending with .py
error: lua script failed: [string "<lua>"]:4: error expanding macro
error: line 95: # Python RPM macro %pycached would help in %files section, as it would avoid

[root@10-75-26-86 ~]# cat /etc/redhat-release
Rocky Linux release 8.5 (Green Obsidian)

**Comment by pvanmda** [comment]
encountered the same issue on RHEL 8.6 - the references to the %pycached and %files macros (even though they're in a comment) need to be escaped with another percent sign (i.e., %%pycached and %%files) to prevent expansion.

a subsequent compile issue was resolved by adding %undefine __brp_mangle_shebangs to allow the #!flask/bin/python shebangs in some .py files to reference a (previously installed) Flask virtual environment (at ~/flask)

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 which is supported on CentOS 8. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
