### ISSUE TITLE
centos7.7 docker build issue

### ISSUE THREAD

**Issue by marks221b** [rackslab/Slurm-web#224]
![image](https://user-images.githubusercontent.com/49939388/174246000-5911fd16-039e-4276-9a02-e172b20d9e32.png)
can anybody give me some advice to solve this error ?

i build slurm-web in my centos 7.7  

my slurm version is 21.08.8-2 

So guys have anyway can run slurm-web in centos7 ?

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on CentOS 8 with RPM packages. For older versions, we plan to distribute containers and this effort is tracked in https://github.com/rackslab/Slurm-web/issues/266.

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
