### ISSUE TITLE
debuild -us -uc Problem....

### ISSUE THREAD

**Issue by gim4moon** [rackslab/Slurm-web#225]
hello.

While installing slurm-web, the message is displayed, but the installation is not possible.

![image](https://user-images.githubusercontent.com/107455607/174538693-95665597-55a3-4280-9a4b-dd0ab3e1f615.png)

I know that apt-get needs to be updated during installation, but I can't proceed because an error occurs in the command.

Any solution?

Thank you.

**Comment by spazzcatt** [comment]
Hello,

It looks like you are missing the dependencies. If you look at the dpkg-checkbuilddeps line that is where the error is. You will need to install the dependencies first to be able to build

**Comment by balajin2022** [comment]
Even i am facing same issue, but now i have installed node-opentypesjs package but again issue is dh_auto_configure: error: pybuild --configure -i python{version} -p 3.10 returned exit code 13

pkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by balajin2022** [comment]
while installing requirements from requirements.txt but i am getting 'ERROR: Could not find a version that satisfies the requirement slurmweb-core (from versions: none)
ERROR: No matching distribution found for slurmweb-core'

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
