### ISSUE TITLE
Unable to configure slurm-web with slurm-rest-api (JWT Authentication)

### ISSUE THREAD

**Issue by KapilS25** [rackslab/Slurm-web#228]
I have a working setup of slurmrest api which uses jwt authentication.
/usr/sbin/slurmrestd -a rest_auth/jwt -s openapi/v0.0.37 -vv 0.0.0.0:9000 -u slurmrestd

Also getting the json output for different requests to slurm api e.x.
curl -H "X-SLURM-USER-NAME:slurmrestd" -H "X-SLURM-USER-TOKEN:${SLURM_JWT}" http://localhost:9000/slurm/v0.0.37/jobs

Need to use X-SLURM-USER-NAME and X-SLURM-USER-TOKEN  in the http headers in order to get it working 
Dont able to get how to use these with slurm-web.

Also I dont have ldap configured on the cluster

can you please guide me on how to setup a slurm web in these case 

I have tried multiple times, every time I gets black screen 

Kindly help 
Looking forward to your response.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
