### ISSUE TITLE
Supported versions of Debian, Ubuntu, etc. for slurm-web 2.4.0?

### ISSUE THREAD

**Issue by mikerenfro** [rackslab/Slurm-web#229]
So the documentation isn't too specific about which versions of Debian, Ubuntu, or other distributions are supported (never mind the Red Hat ecosystem for now).

#222 shows steps required to make slurm-web 2.4.0 work under Ubuntu 20.04 with Slurm 19.05. #213 shows problems with Debian Bullseye.

I've backported enough of Cython, PySlurm, and Slurm to Ubuntu 20.04 to make things work with my Slurm 21.08 cluster, but moving to 22.04 isn't possible without working around the `python3-itsdangerous` package deprecating support for `TimedJSONWebSignatureSerializer` at a minimum.

So can folks add what distributions, versions, and Slurm they've gotten to work with 2.4.0? Notes on how they got it to work would be helpful, too, but may require a lot more effort and verification.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 which is supported on most popular Linux distributions. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
