### ISSUE TITLE
CentOS 7.9 build slurm-web error 

### ISSUE THREAD

**Issue by loveilinux** [rackslab/Slurm-web#230]
Hi all,
  OS version: CentOS 7.9
  Slurm-web: 2.4.0
I run the config  based on the CentOS 8 config ($mock --mount --isolation=simple --root centos-7-x86_64 --buildsrpm --spec /soft/slurm-web-2.4.0/rhel/slurm-web.spec --sources /soft/slurm-web-2.4.0/src --resultdir /root $mock --mount --isolation=simple --root centos-7-x86_64 --rebuild  /root/slurm-web-2.4.0-1.el7.edf.src.rpm --resultdir  /root) . The firest command is ok ,and slurm-web-2.4.0-1.e17.edf.src.rpm is generated , but second command is error.

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.vfkSsd (%build)
    %pycached can only be used with paths explicitly ending with .py
    Bad exit status from /var/tmp/rpm-tmp.vfkSsd (%build)
Finish: rpmbuild slurm-web-2.4.0-1.el7.edf.src.rpm
Finish: build phase for slurm-web-2.4.0-1.el7.edf.src.rpm
ERROR: Exception(/root/slurm-web-2.4.0-1.el7.edf.src.rpm) Config(centos+epel-7-x86_64) 0 minutes 33 seconds
INFO: Results and/or logs in: /root
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/slurm-web.spec

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 with native CentOS8 support. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
