### ISSUE TITLE
Support for RedHat

### ISSUE THREAD

**Issue by wadudmiah** [rackslab/Slurm-web#232]
I have noticed that you have an RPM spec file in the SLURM Web repository:

https://github.com/edf-hpc/slurm-web/blob/master/rhel/slurm-web.spec

Will this build the RPMs for a RedHat-based system? Also, what is the level of support for RedHat-based systems? The documentation does say that support for RedHat is yet to be done, but the RPM spec file seems to suggest there is support for RedHat.

Regards,

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 with native support for RHEL8 and 9. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
