### ISSUE TITLE
Python Error "values of 'package_data' dict" must be a list of strings (got '*.wsgi')

### ISSUE THREAD

**Issue by Nitair-Nomad** [rackslab/Slurm-web#234]
After installing all of the dependancies from here (https://people.debian.org/~ana/slurmweb/) I ran into this error, probably a noob mistake but I'm stumped.

 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package slurm-web
dpkg-buildpackage: info: source version 2.4.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Rémi Palancher <remi-externe.palancher@edf.fr>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 debian/rules clean
dh clean --with apache2 --with python3 --buildsystem pybuild
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/slurm-web'
rm -f dashboard/js/libraries/xdomain.min.js
rm -rf dashboard/js/fonts
make[1]: Leaving directory '/slurm-web'
   dh_clean -O--buildsystem=pybuild
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building slurm-web in slurm-web_2.4.0.tar.xz
dpkg-source: info: building slurm-web in slurm-web_2.4.0.dsc
 debian/rules build
dh build --with apache2 --with python3 --buildsystem pybuild
   dh_update_autotools_config -O--buildsystem=pybuild
   dh_auto_configure -O--buildsystem=pybuild
I: pybuild base:217: python3.8 setup.py config
error in slurm-web setup command: "values of 'package_data' dict" must be a list of strings (got '*.wsgi')
E: pybuild pybuild:341: configure: plugin distutils failed with: exit code=1: python3.8 setup.py config
dh_auto_configure: error: pybuild --configure -i python{version} -p 3.8 returned exit code 13
make: *** [debian/rules:4: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed

**Comment by sdhzlzhk** [comment]
I  edit setup.py below:
....
package_data={'': ['*.wsgi']},
....

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
