### ISSUE TITLE
Repository website link using HTTP

### ISSUE THREAD

**Issue by krishnans2006** [rackslab/slurm-web#237]
The website link in the "About" section of the this repository is `http://rackslab.github.io/slurm-web/`.

When clicked, this takes users to an HTTP version of the slurm-web documentation, instead of the normal HTTPS documentation available at `https://rackslab.github.io/slurm-web/`.

**Comment by rezib** [comment]
Thanks for reporting this. This is weird but this is indeed the default GitHub behaviour. I've just changed the repository settings following [their documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site), it should be fixed now.
