### ISSUE TITLE
GitHub Pages are down: https://rackslab.github.io/slurm-web/

### ISSUE THREAD

**Issue by remram44** [rackslab/Slurm-web#255]
https://rackslab.github.io/slurm-web/ is 404

**Comment by rezib** [comment]
Hi @remram44,

Yes, I broke the URL by mistake when I renamed the repo slurm-web→Slurm-web. I thought GitHub would setup an automatic redirect but I was a bit optimistic.

Anyway, the new official website is now: https://slurm-web.com. The documentation is now available at: https://docs.rackslab.io/slurm-web/overview/start.html

I setup a redirect https://rackslab.github.io/Slurm-web/ → https://slurm-web.com. I guess search engines should update their index quickly.

Please let me know if you have further question.

**Comment by remram44** [comment]
Thanks!
