### ISSUE TITLE
compute name in resource tab too short

### ISSUE THREAD

**Issue by hpc-tau** [rackslab/Slurm-web#302]
for example, if my node name is compute-0-195, I see compute-0.
pressing on it - I get an error, node doesnt exist.
if I fix the url, I see the node
please fix - looks like a ui issue mostly

**Comment by rezib** [comment]
Hey @hpc-tau, thank you for reporting! I will try to reproduce.

**Comment by rezib** [comment]
@hpc-tau, Slurm-web v3.1.0 is now available (https://github.com/rackslab/Slurm-web/discussions/311), can you try it fixes your issue?
