### ISSUE TITLE
Not supported URL scheme http+unix error with Requests 2.25.1-8 on Rocky 9

### ISSUE THREAD

**Issue by rezib** [rackslab/Slurm-web#373]
![3](https://github.com/user-attachments/assets/fea824a6-f81a-42be-b08f-26dfb91f38a5)

**journalctl -u slurm-web-agent-uwsgi.service**

![4](https://github.com/user-attachments/assets/237935f4-5a7c-4202-84be-15a9f1bd0b31)

_Originally posted by @stadox in https://github.com/rackslab/Slurm-web/discussions/372#discussioncomment-11113057_

**Comment by rezib** [comment]
@stadox I am not able to reproduce this issue with these packages on Rocky 9:

```
[root@admin ~]# rpm -qa | egrep 'requests-2|slurm-web'
python3-requests-2.25.1-8.el9.noarch
python3-slurm-web-3.2.0-1.el9.noarch
slurm-web-agent-3.2.0-1.el9.noarch
slurm-web-gateway-3.2.0-1.el9.noarch
```

I just figured out of your logs that Slurm-web and requests Python packages are installed in `/usr/local`. I guess you installed Slurm-web from source, right? Note that only [installations from distributions packages](https://docs.rackslab.io/slurm-web/install/install/distribs/index.html) are supported.

**Comment by stadox** [comment]
Hello,

I tried to install it following https://docs.rackslab.io/slurm-web/install/install/distribs/rocky.html

**Comment by stadox** [comment]
Hello,

I installed packages following https://docs.rackslab.io/slurm-web/install/install/distribs/rocky.html

[root@model07 self]# rpm -qa | egrep 'requests-2|slurm-web'
python3-requests-2.25.1-8.el9.noarch
python3-slurm-web-3.2.0-1.el9.noarch
slurm-web-agent-3.2.0-1.el9.noarch
slurm-web-gateway-3.2.0-1.el9.noarch

but still the same

![log](https://github.com/user-attachments/assets/2b9b913e-5e03-44b3-926e-f2d9cceea4fc)

thank you very much 

Kind regards,
Stanislav

**Comment by rezib** [comment]
You can see in the logs that it is still loading Requests library installed in `/usr/local`, instead of Requests library of `python3-requests` package.

**Comment by stadox** [comment]
Hi,

I tried to resolve this case for python /usr/local/....

It seems that point Requests library to /usr/lib/.... 

**helped and now I'm able to see the GUI interface over uwsgi.sock**

What left now for me is to find a route cause is this this message appears only on Dashboard card.
Other TABS (Jobs, Resources,... ) are working well.

![dashboard](https://github.com/user-attachments/assets/45d90c4e-a81a-400c-8cab-cb39f502c343)

![log](https://github.com/user-attachments/assets/c3bb85cf-c64d-441b-9e90-2ff5f1debfb3)


Thank you a lot for support and time!

Regards,
Stanislav

**Comment by rezib** [comment]
I close this issue as the initial issue is fixed. Your are asking about something else now, please open another Q&A discussion with your new help request.
