### ISSUE TITLE
Add more columns in the Partitions view

### ISSUE THREAD

**Issue by mehdid** [rackslab/Slurm-web#43]
It should be possible to add the following columns:
- def_mem_per_cpu
- max_mem_per_cpu
- deny_accounts
- deny_qos
- allow_qos
- priority
- default_time
- allow_accounts
- max_cpus_per_node
- max_share
- allow_groups

**Comment by rezib** [comment]
We want to fix this issue wisely with #146 in mind. This issue is pending for update on #146 before going further.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
