### ISSUE TITLE
 Add layout(s) view 

### ISSUE THREAD

**Issue by ghost** [rackslab/Slurm-web#44]
A layout is defined as a tree (for the moment).
The idea is to draw a graph that shows all elements (entity) of a layout.
Ability to click on entities to show current key/values on this entity.
Ability to have link to other layouts using this entity.
Ability to show concerned jobs (if entity is a node).

**Comment by mehdid** [comment]
This looks interesting but I think it needs adding bindings in pyslurm first

**Comment by thomderainette** [comment]
Agree.
Layouts are new (really included in slurm 15-08)
The functions to see layouts are bases on "scontrol show layouts=..."

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
