### ISSUE TITLE
Charts legend not consistent across browsers

### ISSUE THREAD

**Issue by hmlth** [rackslab/Slurm-web#57]
![bugreport-slurmwebb](https://cloud.githubusercontent.com/assets/11946481/10887016/21e1f460-8185-11e5-9400-81a639e879ed.png)

In the screenshot, chromium and iceweasel on debian. Maybe due to some list ordering differences.

**Comment by mehdid** [comment]
But data is consistent, right?

**Comment by hmlth** [comment]
I think so.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
