### ISSUE TITLE
Specifying nodesets in ID attributes in not allowed by XML spec

### ISSUE THREAD

**Issue by rezib** [rackslab/Slurm-web#66]
Example of error on XML validation:

```
# xmllint --valid --noout /etc/slurm-web/racks.xml
/etc/slurm-web/racks.xml:15: element nodeset: validity error : Syntax of value for attribute id of nodeset is not valid
          <nodeset id="pocn[001-036]" type="nx360" posy="3" />
                                                            ^
/etc/slurm-web/racks.xml:16: element nodeset: validity error : Syntax of value for attribute id of nodeset is not valid
          <nodeset id="pocn[037-072]" type="nx360" posy="23" />
                                                             ^
```

Spec is here: http://www.w3.org/TR/xml/#sec-attribute-types

The `id` attribute must renamed, eg. `nodes`.

**Comment by Lorel** [comment]
the dash char is not accepted

**Comment by mehdid** [comment]
My take is that there is a bug in the XML spec ;-)

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
