### ISSUE TITLE
Debian 8 missing packages on 2.0.0

### ISSUE THREAD

**Issue by jbaksta** [rackslab/Slurm-web#92]
Hello, I had slurm-web (1.1.3) running in Debian 8 for quite some time, but with the 2.0.0 I've finally got around to trying out, there are quite a few more required packages which are not in the repos for Debian 8. I'm not a Debian expert and Debian is not my daily OS so perhaps I missed something small too, however the missing packages from the apt-get install command are below:

```
The following packages have unmet dependencies:
 slurm-web-dashboard : Depends: libjs-requirejs but it is not installable
                       Depends: libjs-requirejs-text but it is not installable
                       Depends: libjs-three but it is not installable
                       Depends: libjs-bootstrap-typeahead but it is not installable
                       Depends: libjs-bootstrap-tagsinput but it is not installable
```

So far I have found that `libjs-requirejs` and `libjs-requirejs-text` I believe have been renamed to `node-requirejs` and `node-requirejs-text` respectively. However, the other three I've not quite determined.

My question would be is there value in perhaps keeping a separate branch for Debian 8 if there an unclean method to make the slurm-web packages Debian version agnostic? I'm attempting to guess the best way to solve this Debian issue. Perhaps I'm also just missing something here. 

Maybe somebody else running Debian 8 can chime in?

**Comment by rezib** [comment]
Hi Jared,

I'm very happy to count yourself as a slurm-web user :)

Yes, new 2.0 version brings quite a lot of new features that requires new JS deps along. And indeed, these deps are not available in Debian for the moment (in 8.0 and even in others versions too). That's why we have developed those packages ourselves.

Unfortunately, I don't have enough time in the following days to install and configure a public debian APT repository (with GPG keys and so on,  but I will upload those packages on a public HTTP server so you can download them in an easy way.

**Comment by rezib** [comment]
Hi Jared,

Thanks to a friend @ana, we've uploaded the missing packages on Debian development server, and I added a quick how-to on the wiki: https://github.com/edf-hpc/slurm-web/wiki

You should check it out. For the moment, it should do the job, until the proper solution with dedicated slurm-web RPM and DEB repositories.

**Comment by jbaksta** [comment]
Thanks Remi, I will have a look in the nearish future and hopefully report back with good results and any findings that I have.

**Comment by mehdid** [comment]
For reference, we eventually published slurm-web (and all its dependencies) on scibian's APT repository: https://scibian.org/repo/

Scibian8 repository works with Debian8 repositories.

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 for which the quick start guide is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Note that Slurm-web v3.0.0 is officially supported on many Debian versions, from stable to sid with deb packages.

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
