### ISSUE TITLE
Add an "Issues" view

### ISSUE THREAD

**Issue by mehdid** [rackslab/Slurm-web#93]
Such view should list known issues (drain reasons, down nodes, dates about issues, users, ...)

**Comment by rezib** [comment]
This issue concerns Slurm-web v2 which is not maintained anymore. You are highly encouraged to test the new version v3.0.0 that is not impacted by this issue. The quick start guide for v3.0.0 is available online: https://docs.rackslab.io/slurm-web/install/quickstart.html

Unless someone is motivated to maintain the old version of Slurm-web or you have a justified reason to keep this issue open, it will be closed in a few weeks.

**Comment by rezib** [comment]
For the reasons explained in the previous comment, I finally close this issue.
